--[[
    brspectate -- the console pointing a moderator at a player.

    THE SECOND CONSOLE VERB THAT REACHES INTO A RUNNING MATCH, after the kick,
    and it is deliberately built as the same shape rather than as something new:

        Ringmaster  --ssh-->  dispatch.sh  --tmux send-keys-->  this console
                                                                     |
                                     brspectate <admin> <target> <cmdId>
                                                                     |
                                       br:core:spectate -> br_core
                                                                     |
                                        outcome event back, and an
                                        admin_spectate row for the log

    LICENSES, NEVER SERVER IDS, and this is the whole reason the two arguments
    are the shape they are. Server ids are recycled within the minute, so a
    console rendered thirty seconds ago holds ids that may now belong to somebody
    else -- the exact hazard kick.lua's findByLicense exists for, and a worse one
    here: a kick against the wrong id removes somebody, while a spectate against
    the wrong id points a camera at a player nobody was authorised to watch.

    IT IS LIGHTER THAN THE KICK IN ONE RESPECT AND HEAVIER IN ANOTHER. Nothing
    here removes anyone, and there is no free-text argument at all -- both
    arguments are hex licenses and a UUID, all three generated by us, so there is
    no untrusted string to strip and no way for a payload to become a second
    console line. What is heavier is that the subject does not know: an admin
    watching a player who has not been told is exactly the class of action
    `ringmaster-audit` exists to record, which is why the outcome is only half of
    what goes back -- see BR.Ring.emitSpectate in push.lua.

    THIS RESOURCE DOES NOT KNOW WHAT SPECTATING IS. It resolves two licenses to
    two server ids and hands them to br_core, which owns the session, the camera
    feed and the policy. That keeps the direction right: br_core never depends on
    br_ringmaster, and br_ringmaster still declares no dependency on br_core --
    an event into a resource that is not running simply finds no handler, and the
    outcome reports the refusal.
]]

BR = BR or {}
BR.Ring = BR.Ring or {}

--- Find the connected player holding this license.
---
--- A SECOND COPY OF kick.lua's findByLicense, ON PURPOSE. That one is inside the
--- file verify.sh pins DropPlayer to, and the whole value of that pin is that the
--- file stays small and reviewable. Exporting its internals so this file could
--- share them would widen the reviewed surface to gain eight lines.
--- @param license string
--- @return number|nil src
local function findByLicense(license)
    for _, src in ipairs(GetPlayers()) do
        local byKind = BR.Identity.ofPlayer(src)
        if BR.Identity.qualified('license', byKind.license) == license then
            return tonumber(src)
        end
    end
    return nil
end

local function report(commandId, ok, detail)
    if not commandId or commandId == '' then return end
    if BR.Ring.emitOutcome then
        BR.Ring.emitOutcome(commandId, ok, detail)
    end
end

--- Command ids we have asked br_core about and not yet heard back on.
---
--- IT IS ONLY EVER EMPTY OR HOLDING ONE ENTRY, and that is a property of
--- FiveM's own event dispatch rather than luck: a server-side TriggerEvent runs
--- its handlers INLINE, so br_core answers before the call below returns. The
--- table exists to make "nobody answered" observable at all -- see the end of
--- the command.
local awaiting = {}

--- br_core's answer to a start we asked for.
---
--- THE OUTCOME IS STAMPED FROM HERE AND NOT FROM br_core, because the command id
--- is the console's and the audit row it joins is the console's -- br_core has
--- no idea either exists. It is handed the id, echoes it back, and this closes
--- the loop. Same two-phase shape as the kick.
AddEventHandler('br:core:spectateResult', function(res)
    if type(res) ~= 'table' then return end
    awaiting[tostring(res.commandId)] = nil
    if res.ok then
        print(('^2[br_ringmaster] spectate started: %s^7'):format(tostring(res.detail)))
        report(res.commandId, true, { started = true, target = res.detail })
    else
        print(('^3[br_ringmaster] spectate refused: %s^7'):format(tostring(res.detail)))
        report(res.commandId, true, { started = false, reason = res.detail })
    end
end)

RegisterCommand('brspectate', function(source, args)
    -- Console only. `source` is 0 for the server console, which is the only
    -- caller this command has: dispatch.sh types it in through tmux. A player
    -- invoking it would arrive with their own id.
    if source ~= 0 then
        return
    end

    local adminLicense, targetLicense, commandId = args[1], args[2], args[3]

    if type(adminLicense) ~= 'string' or not adminLicense:match('^license2?:%x+$')
       or type(targetLicense) ~= 'string' or not targetLicense:match('^license2?:%x+$') then
        print('^1[br_ringmaster] brspectate: bad license^7')
        report(commandId, false, { error = 'bad license' })
        return
    end

    local adminSrc = findByLicense(adminLicense)
    local targetSrc = findByLicense(targetLicense)

    -- BOTH ENDS MUST BE HERE, AND NEITHER ABSENCE IS AN ERROR. The console only
    -- offers the button when both are in-game -- hidden, not greyed, per the
    -- standing rule -- so reaching this line means the board was stale by a few
    -- seconds. Reporting it as a failure would send an admin chasing a fault
    -- that is really just a page that needs refreshing.
    if not adminSrc then
        print(('^3[br_ringmaster] brspectate: admin %s is not connected^7')
            :format(adminLicense))
        report(commandId, true, { started = false, reason = 'admin not connected' })
        return
    end
    if not targetSrc then
        print(('^3[br_ringmaster] brspectate: target %s is not connected^7')
            :format(targetLicense))
        report(commandId, true, { started = false, reason = 'target not connected' })
        return
    end

    local key = tostring(commandId)
    awaiting[key] = true

    TriggerEvent('br:core:spectate', {
        admin         = adminSrc,
        target        = targetSrc,
        adminLicense  = adminLicense,
        targetLicense = targetLicense,
        commandId     = commandId,
    })

    -- NOBODY ANSWERED, WHICH MEANS THE GAMEMODE IS NOT RUNNING.
    --
    -- `restart br_core` is what tools/deploy.sh tells you to run after every
    -- deploy, and this resource deliberately does not depend on br_core so that
    -- moderation survives it. The cost of that independence is exactly this
    -- window -- and without this line an admin who pressed Spectate inside it
    -- would get an audit row stuck at "unacknowledged" forever, which the log
    -- shows as "we asked and never found out". That is the right state for a
    -- command whose fate is genuinely unknown, and the wrong one here: we know.
    if awaiting[key] then
        awaiting[key] = nil
        print('^3[br_ringmaster] brspectate: br_core did not answer -- '
              .. 'is the gamemode running?^7')
        report(commandId, false, { error = 'gamemode not running' })
    end
end, true)
