#!/usr/bin/env python3
"""Licensed assets: purchased resources the boxes run but this repo never holds (#391).

    py tools/assets.py push <folder> [--season N] [--from N] [--until N]   on the owner's PC
    python3 tools/assets.py pull [--dry-run]                               on a game box (deploy.sh runs it)
    py tools/assets.py status [--profile blitz-assets]                     lock vs installed vs bucket
    py tools/assets.py check                                               verify.sh and CI

WHY THIS EXISTS. The NTeam Legion map pack and the emote packs for #215 were
bought, and their licenses do not allow redistribution. This repository is
PUBLIC, so they can never be committed to it. They live in a private S3 bucket
instead, one archive per version, and assets.lock at the repo root pins which
version each box runs: a commit bumps an asset, `git revert` rolls it back, dev
deploys run dev's lock and prod runs main's, so assets ship with an episode PR
the way code does.

THE LOCK HOLDS NAMES, HASHES, SIZES, FILE LISTS AND SEASON PINS, AND NOTHING
ELSE. `check` refuses any other key. The file lists are there so a test or an
agent can check that our code's references (anim dicts, model names) exist in
a pack without having the pack.

SEASONS (#388). An entry maps seasons to versions; the version in force is the
one pinned at the newest season at or below the box's season, exactly like
BR.Season.pick. `from` and `until` bound the whole entry the way a row in
br_lib/config/seasons.lua is bounded by `from` and `untilSeason`: on from Season
`from`, off again from Season `until`. A resource with no version for the box's
season is not installed. The box's season is br_season as its server.cfg sets
it (exec'd files followed); unset means `latest` in seasons.lua, as in game.

THREE RULES THE CODE BELOW EXISTS TO KEEP, each pinned by tools/test_assets.py:

  * EVERY ARCHIVE'S SHA256 IS CHECKED BEFORE IT IS UNPACKED. fetch_verified()
    is the only door to an archive path, and pull unpacks nothing until every
    archive it needs has come through it.
  * NOTHING OUTSIDE resources/[licensed]/ IS EVER REMOVED OR REPLACED, and a
    failed pull leaves what was installed exactly as it was: everything is
    downloaded, verified and unpacked into a staging directory first, and only
    then swapped in, with every move undone if one fails.
  * AN OBJECT IN THE BUCKET IS NEVER OVERWRITTEN. The key is the archive's own
    sha256, so a different archive is a different key, and push skips the
    upload when the key exists.

Stdlib only, and the transfers go through the `aws` CLI so credentials stay
with the CLI: a profile on the owner's PC, the instance role on a box. This
file never reads them.
"""

from __future__ import annotations

import argparse
import contextlib
import gzip
import hashlib
import json
import os
import re
import shutil
import stat
import subprocess
import sys
import tarfile
import tempfile

BUCKET = 'blitz-royale-assets'
REGION = 'us-east-2'
KEY_PREFIX = 'assets/'
PUSH_PROFILE = 'blitz-assets'

LOCK_NAME = 'assets.lock'
LOCK_FORMAT = 1

# Where a box keeps them. resources/[licensed]/ belongs to this tool: deploy.sh
# never syncs into it, and a pull may remove any resource directory inside it
# that the lock does not list for the box's season.
LICENSED_GROUP = '[licensed]'
CFG_FILE = 'licensed.cfg'
# The install record, inside a resource so br_core can read it: FXServer's Lua
# sandbox refuses io outside resource folders, and LoadResourceFile needs the
# resource only to be known to the server, not started. Never ensured.
# br_core/server/season.lua names both strings; tools/test_season.lua pins them.
RECORD_RESOURCE = 'br_licensed'
RECORD_FILE = 'installed.txt'
CACHE_DIR = '.assets-cache'
DEFAULT_SERVER_ROOT = '/opt/fivem-server-classic'

SEASONS_LUA = ('resources', '[fivem-royale]', 'br_lib', 'config', 'seasons.lua')
SEASON_CONVAR = 'br_season'
MAX_SEASON = 9999

TOOL_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(TOOL_DIR)

NAME_RE = re.compile(r'[A-Za-z0-9_][A-Za-z0-9_-]{0,63}\Z')
SHA_RE = re.compile(r'[0-9a-f]{64}\Z')
SEASON_KEY_RE = re.compile(r'[1-9][0-9]{0,3}\Z')

# Left out of a pack, so the same resource packs to the same sha on a machine
# whose file browser has been in the folder.
JUNK_FILES = frozenset(('thumbs.db', 'desktop.ini', '.ds_store'))
JUNK_DIRS = frozenset(('.git', '.svn', '.hg'))

ENTRY_KEYS = ('name', 'from', 'until', 'seasons', 'versions')
VERSION_KEYS = ('size', 'files')

RECORD_MANIFEST = """\
-- GENERATED by tools/assets.py pull (#391). Do not edit, and do not ensure it:
-- br_core reads installed.txt out of it with LoadResourceFile, which needs the
-- resource to be known to the server, not started.
fx_version 'cerulean'
game 'gta5'
"""


class AssetsError(Exception):
    """A refusal with a message for the operator. Exit 1, nothing changed."""


def say(msg: str = '') -> None:
    print(('assets: ' + msg) if msg else '', flush=True)


def human(n: int) -> str:
    size = float(n)
    for unit in ('B', 'KB', 'MB', 'GB'):
        if size < 1024 or unit == 'GB':
            return ('%d %s' % (size, unit)) if unit == 'B' else ('%.1f %s' % (size, unit))
        size /= 1024
    return '%d B' % n


def short(sha: str) -> str:
    return sha[:12]


def object_key(name: str, sha: str) -> str:
    return '%s%s/%s.tar.gz' % (KEY_PREFIX, name, sha)


def sha256_file(path: str) -> tuple[str, int]:
    h = hashlib.sha256()
    n = 0
    with open(path, 'rb') as fh:
        while True:
            block = fh.read(1 << 20)
            if not block:
                break
            h.update(block)
            n += len(block)
    return h.hexdigest(), n


def is_int(v) -> bool:
    return isinstance(v, int) and not isinstance(v, bool)


def bad_rel_path(p) -> str | None:
    """Why a path from a pack, an archive or the lock is unsafe, or None.

    Relative, forward slashes, no empty, `.` or `..` segment, no drive letter,
    no control character. An archive member that passes cannot land outside
    the directory it is unpacked into.
    """
    if not isinstance(p, str) or not p:
        return 'empty path'
    if len(p) > 400:
        return 'path longer than 400 characters'
    if '\\' in p:
        return 'backslash in path'
    if p.startswith('/'):
        return 'absolute path'
    if re.match(r'[A-Za-z]:', p):
        return 'drive letter in path'
    if any(ord(c) < 32 or ord(c) == 127 for c in p):
        return 'control character in path'
    if any(part in ('', '.', '..') for part in p.split('/')):
        return 'empty, "." or ".." segment in path'
    return None


def atomic_write(path: str, text: str) -> None:
    tmp = '%s.tmp-%d' % (path, os.getpid())
    with open(tmp, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(text)
    os.replace(tmp, path)


def read_bytes(path: str) -> bytes | None:
    try:
        with open(path, 'rb') as fh:
            return fh.read()
    except FileNotFoundError:
        return None


def is_link(path: str) -> bool:
    if os.path.islink(path):
        return True
    isjunction = getattr(os.path, 'isjunction', None)
    return bool(isjunction and isjunction(path))


# --------------------------------------------------------------------------
# packing
# --------------------------------------------------------------------------

def collect(folder: str) -> tuple[list[tuple[str, str, int]], list[str]]:
    """The files a pack holds, as (relative path, full path, size), sorted.

    Plain files only: a link anywhere in the folder is refused rather than
    followed, because what it points at is not part of the resource.
    """
    root = os.path.abspath(folder)
    files: list[tuple[str, str, int]] = []
    skipped: list[str] = []

    def rel(full):
        return os.path.relpath(full, root).replace(os.sep, '/')

    for dirpath, dirnames, filenames in os.walk(root, followlinks=False):
        keep = []
        for d in dirnames:
            full = os.path.join(dirpath, d)
            if is_link(full):
                raise AssetsError('%s is a link; a resource folder must hold plain files only' % rel(full))
            if d.lower() in JUNK_DIRS:
                skipped.append(rel(full) + '/')
                continue
            keep.append(d)
        dirnames[:] = keep
        for f in filenames:
            full = os.path.join(dirpath, f)
            relp = rel(full)
            if f.lower() in JUNK_FILES:
                skipped.append(relp)
                continue
            st = os.lstat(full)
            if stat.S_ISLNK(st.st_mode) or is_link(full):
                raise AssetsError('%s is a link; a resource folder must hold plain files only' % relp)
            if not stat.S_ISREG(st.st_mode):
                raise AssetsError('%s is not a regular file' % relp)
            why = bad_rel_path(relp)
            if why:
                raise AssetsError('%s: %s' % (relp, why))
            files.append((relp, full, st.st_size))
    files.sort(key=lambda t: t[0].encode('utf-8'))
    return files, sorted(skipped)


def pack(folder: str, out_path: str) -> tuple[dict[str, int], list[str]]:
    """Pack a resource folder into a .tar.gz, deterministically.

    THE SAME FOLDER ALWAYS GIVES THE SAME BYTES, so pushing an unchanged pack is
    a no-op rather than a new version: entries sorted, no directory entries,
    mtime 0, owner 0:0 with no names, mode 0644, and a gzip header with no file
    name and no timestamp. Paths are relative to the folder, so the resource's
    name comes from the lock and never from inside an archive.
    """
    files, skipped = collect(folder)
    if not any(relp == 'fxmanifest.lua' for relp, _, _ in files):
        raise AssetsError('%s has no fxmanifest.lua at its top; it is not a FiveM resource folder' % folder)
    with open(out_path, 'wb') as raw:
        with gzip.GzipFile(filename='', mode='wb', fileobj=raw, compresslevel=6, mtime=0) as gz:
            with tarfile.open(fileobj=gz, mode='w', format=tarfile.PAX_FORMAT, encoding='utf-8') as tar:
                for relp, full, size in files:
                    info = tarfile.TarInfo(relp)
                    info.size = size
                    info.mtime = 0
                    info.mode = 0o644
                    info.uid = info.gid = 0
                    info.uname = info.gname = ''
                    info.type = tarfile.REGTYPE
                    with open(full, 'rb') as fh:
                        tar.addfile(info, fh)
    return {relp: size for relp, _, size in files}, skipped


def unpack(archive: str, dest: str, files: dict[str, int]) -> None:
    """Write a VERIFIED archive's files into `dest`, which must not exist yet.

    Only ever handed a path fetch_verified() returned. Regular files only, each
    path checked by bad_rel_path, nothing ever overwritten, and the result must
    be exactly the lock's file list.
    """
    os.makedirs(dest)
    seen: dict[str, int] = {}
    with tarfile.open(archive, mode='r:gz') as tar:
        for m in tar:
            why = bad_rel_path(m.name)
            if why:
                raise AssetsError('archive member %r: %s' % (m.name, why))
            if m.isdir():
                continue
            if not m.isreg():
                raise AssetsError('archive member %r is not a regular file' % m.name)
            if m.name in seen:
                raise AssetsError('archive member %r appears twice' % m.name)
            target = os.path.join(dest, *m.name.split('/'))
            os.makedirs(os.path.dirname(target), exist_ok=True)
            src = tar.extractfile(m)
            with open(target, 'xb') as out:
                shutil.copyfileobj(src, out, 1 << 20)
            seen[m.name] = m.size
    if seen != files:
        raise AssetsError("the archive's files differ from the file list in assets.lock")


def dir_files(path: str) -> dict[str, int]:
    out: dict[str, int] = {}
    for dirpath, _dirnames, filenames in os.walk(path):
        for f in filenames:
            full = os.path.join(dirpath, f)
            out[os.path.relpath(full, path).replace(os.sep, '/')] = os.path.getsize(full)
    return out


# --------------------------------------------------------------------------
# the lock
# --------------------------------------------------------------------------

def _no_duplicate_keys(pairs):
    out = {}
    for k, v in pairs:
        if k in out:
            raise AssetsError('assets.lock: the key %r appears twice in one object' % k)
        out[k] = v
    return out


def parse_lock_text(text: str):
    if text.startswith('\ufeff'):
        text = text[1:]
    try:
        return json.loads(text, object_pairs_hook=_no_duplicate_keys)
    except json.JSONDecodeError as e:
        raise AssetsError('assets.lock is not valid JSON: %s' % e)


def repo_resource_names(root: str = REPO_ROOT) -> frozenset[str]:
    """Lower-cased names of the resources this repository ships. A licensed
    resource may not share one: FiveM would see two resources with one name."""
    names = set()
    base = os.path.join(root, 'resources')
    for dirpath, dirnames, filenames in os.walk(base):
        dirnames[:] = [d for d in dirnames if d != 'node_modules' and not d.startswith('.')]
        if 'fxmanifest.lua' in filenames or '__resource.lua' in filenames:
            names.add(os.path.basename(dirpath).lower())
            dirnames[:] = []
    return frozenset(names)


def validate(data, repo_names: frozenset[str] = frozenset()) -> list[str]:
    """Every way the lock is wrong, or [] when it is right."""
    p: list[str] = []
    if not isinstance(data, dict):
        return ['the lock must be a JSON object']
    extra = sorted(set(data) - {'format', 'resources'})
    if extra:
        p.append('unknown top-level key(s) %s: a lock holds names, hashes, sizes, '
                 'file lists and season pins, nothing else' % ', '.join(extra))
    if data.get('format') != LOCK_FORMAT or not is_int(data.get('format')):
        p.append('"format" must be %d' % LOCK_FORMAT)
    res = data.get('resources')
    if not isinstance(res, list):
        p.append('"resources" must be a list')
        return p
    seen: set[str] = set()
    for i, e in enumerate(res):
        where = 'resources[%d]' % i
        if not isinstance(e, dict):
            p.append('%s is not an object' % where)
            continue
        name = e.get('name')
        if isinstance(name, str) and name:
            where = name
        extra = sorted(set(e) - set(ENTRY_KEYS))
        if extra:
            p.append('%s: unknown key(s) %s (allowed: %s)' % (where, ', '.join(extra), ', '.join(ENTRY_KEYS)))
        if not isinstance(name, str) or not NAME_RE.match(name):
            p.append('%s: "name" must be a resource name: letters, digits, _ and -, at most 64' % where)
        else:
            low = name.lower()
            if low in seen:
                p.append('%s: listed twice' % name)
            seen.add(low)
            if low == RECORD_RESOURCE:
                p.append('%s: the name is reserved for the install record' % name)
            if low in repo_names:
                p.append('%s: a resource in this repository already has that name' % name)
        frm, until = e.get('from'), e.get('until')
        for key, v in (('from', frm), ('until', until)):
            if key in e and (not is_int(v) or not 1 <= v <= MAX_SEASON):
                p.append('%s: "%s" must be a season, a whole number from 1' % (where, key))
        if is_int(frm) and is_int(until) and until <= frm:
            p.append('%s: "until" (%d) must be after "from" (%d)' % (where, until, frm))
        seasons = e.get('seasons')
        if not isinstance(seasons, dict) or not seasons:
            p.append('%s: "seasons" must map at least one season to a sha256' % where)
            seasons = {}
        pinned: set[str] = set()
        for k, sha in seasons.items():
            good_key = bool(SEASON_KEY_RE.match(k))
            if not good_key:
                p.append('%s: %r is not a season (a whole number from 1, no leading zero)' % (where, k))
            if not isinstance(sha, str) or not SHA_RE.match(sha):
                p.append('%s: Season %s: %r is not a sha256 (64 lowercase hex)' % (where, k, sha))
                continue
            pinned.add(sha)
            if good_key and is_int(until) and int(k) >= until:
                p.append('%s: the version pinned at Season %s is never in force ("until" is %d)' % (where, k, until))
        versions = e.get('versions')
        if not isinstance(versions, dict):
            p.append('%s: "versions" must be an object keyed by sha256' % where)
            versions = {}
        for sha, v in versions.items():
            if not SHA_RE.match(sha):
                p.append('%s: version key %r is not a sha256' % (where, sha))
                continue
            if sha not in pinned:
                p.append('%s: version %s is pinned to no season; drop it (git history keeps it)' % (where, short(sha)))
            if not isinstance(v, dict):
                p.append('%s: version %s is not an object' % (where, short(sha)))
                continue
            extra = sorted(set(v) - set(VERSION_KEYS))
            if extra:
                p.append('%s: version %s: unknown key(s) %s (allowed: size, files)' % (where, short(sha), ', '.join(extra)))
            if not is_int(v.get('size')) or v.get('size') <= 0:
                p.append('%s: version %s: "size" must be the archive size in bytes' % (where, short(sha)))
            files = v.get('files')
            if not isinstance(files, dict) or not files:
                p.append('%s: version %s: "files" must map each path in the archive to its size' % (where, short(sha)))
                continue
            for path, n in files.items():
                why = bad_rel_path(path)
                if why:
                    p.append('%s: version %s: %r: %s' % (where, short(sha), path, why))
                if not is_int(n) or n < 0:
                    p.append('%s: version %s: %r: size must be a whole number of bytes' % (where, short(sha), path))
            if 'fxmanifest.lua' not in files:
                p.append('%s: version %s has no fxmanifest.lua at its top' % (where, short(sha)))
        for sha in sorted(pinned - set(versions)):
            p.append('%s: %s is pinned to a season but has no entry under "versions"' % (where, short(sha)))
    return p


def load_lock(path: str, repo_names: frozenset[str] | None = None) -> dict:
    """The lock, validated. An absent lock is an empty one."""
    raw = read_bytes(path)
    if raw is None:
        return {'format': LOCK_FORMAT, 'resources': []}
    data = parse_lock_text(raw.decode('utf-8', 'replace'))
    problems = validate(data, repo_resource_names() if repo_names is None else repo_names)
    if problems:
        raise AssetsError('%s does not pass check:\n%s' % (path, '\n'.join('  ' + x for x in problems)))
    return data


def dump_lock(lock: dict) -> str:
    """The lock as it is written: one field per line, in a fixed order."""
    out = []
    for e in lock['resources']:
        o = {'name': e['name']}
        for k in ('from', 'until'):
            if k in e:
                o[k] = e[k]
        keys = sorted(e['seasons'], key=int)
        o['seasons'] = {k: e['seasons'][k] for k in keys}
        order: list[str] = []
        for k in keys:
            if e['seasons'][k] not in order:
                order.append(e['seasons'][k])
        o['versions'] = {
            sha: {
                'size': e['versions'][sha]['size'],
                'files': {f: e['versions'][sha]['files'][f]
                          for f in sorted(e['versions'][sha]['files'], key=lambda s: s.encode('utf-8'))},
            }
            for sha in order
        }
        out.append(o)
    return json.dumps({'format': LOCK_FORMAT, 'resources': out}, indent=2, ensure_ascii=False) + '\n'


def version_for(entry: dict, season: int) -> str | None:
    """The sha in force for `season`: the one pinned at the newest season at or
    below it, inside from/until -- or None, and the resource is not installed."""
    frm, until = entry.get('from'), entry.get('until')
    if frm is not None and season < frm:
        return None
    if until is not None and season >= until:
        return None
    best = None
    for k, sha in entry['seasons'].items():
        n = int(k)
        if n <= season and (best is None or n > best[0]):
            best = (n, sha)
    return best[1] if best else None


def plan_for(lock: dict, season: int) -> list[tuple[str, str, dict]]:
    """(name, sha, version) for every resource in force, in lock order."""
    out = []
    for e in lock['resources']:
        sha = version_for(e, season)
        if sha is not None:
            out.append((e['name'], sha, e['versions'][sha]))
    return out


# --------------------------------------------------------------------------
# the box's season
# --------------------------------------------------------------------------

def read_latest(repo_root: str = REPO_ROOT) -> int:
    path = os.path.join(repo_root, *SEASONS_LUA)
    try:
        with open(path, encoding='utf-8', errors='replace') as fh:
            text = fh.read()
    except OSError:
        raise AssetsError('cannot read %s, which says the latest season' % path)
    m = re.search(r'^[ \t]*latest[ \t]*=[ \t]*([0-9]+)', text, re.M)
    if not m or int(m.group(1)) < 1:
        raise AssetsError('no `latest = <n>` in %s' % path)
    return int(m.group(1))


def parse_season(raw) -> int | None:
    """BR.Season.parse: a whole number from 1, digits only, spaces forgiven."""
    if not isinstance(raw, str):
        return None
    s = raw.strip()
    if not re.match(r'[0-9]+\Z', s):
        return None
    n = int(s)
    return n if 1 <= n <= MAX_SEASON else None


def cfg_tokens(line: str) -> list[str]:
    """One cfg line as FXServer splits it: whitespace, double quotes, and a
    comment from a `#` or `//` that starts a token."""
    toks: list[str] = []
    i, n = 0, len(line)
    while i < n:
        c = line[i]
        if c.isspace():
            i += 1
            continue
        if c == '"':
            j = line.find('"', i + 1)
            if j < 0:
                j = n
            toks.append(line[i + 1:j])
            i = j + 1
            continue
        if c == '#' or line.startswith('//', i):
            break
        j = i
        while j < n and not line[j].isspace() and line[j] != '"':
            j += 1
        toks.append(line[i:j])
        i = j
    return toks


def cfg_season(server_root: str, cfg_path: str) -> tuple[tuple[str, str, int] | None, list[str]]:
    """The last value server.cfg gives br_season, following exec, as
    (value, file, line), plus notes on anything that could not be followed."""
    found: list = [None]
    notes: list[str] = []
    seen: set[str] = set()

    def walk(path: str, depth: int) -> None:
        key = os.path.normcase(os.path.abspath(path))
        if key in seen:
            return
        if depth > 16:
            notes.append('%s: exec nested too deep, not followed' % path)
            return
        seen.add(key)
        raw = None
        try:
            raw = read_bytes(path)
        except OSError as e:
            notes.append('%s: %s' % (path, e.strerror or e))
            return
        if raw is None:
            notes.append('%s does not exist' % path)
            return
        for lineno, line in enumerate(raw.decode('utf-8', 'replace').splitlines(), 1):
            t = cfg_tokens(line)
            if not t:
                continue
            cmd = t[0].lower()
            if cmd in ('set', 'setr', 'sets', 'seta') and len(t) >= 3 and t[1].lower() == SEASON_CONVAR:
                found[0] = (t[2], path, lineno)
            elif cmd == SEASON_CONVAR and len(t) >= 2:
                found[0] = (t[1], path, lineno)
            elif cmd == 'exec' and len(t) >= 2:
                target = t[1]
                if target.startswith('@'):
                    notes.append('%s:%d: exec %s is inside a resource; not followed' % (path, lineno, target))
                    continue
                walk(target if os.path.isabs(target) else os.path.join(server_root, target), depth + 1)

    walk(cfg_path, 0)
    return found[0], notes


def resolve_season(args, server_root: str, latest: int) -> tuple[int, str]:
    if getattr(args, 'season', None) is not None:
        return args.season, '--season %d' % args.season
    cfg = args.server_cfg or os.path.join(server_root, 'server.cfg')
    found, notes = cfg_season(server_root, cfg)
    for n in notes:
        say('note: ' + n)
    if found is None:
        return latest, '%s is not set: the latest' % SEASON_CONVAR
    raw, path, lineno = found
    n = parse_season(raw)
    where = '%s:%d' % (os.path.basename(path), lineno)
    if n is None:
        say('warning: %s %r (%s) is not a season; using the latest, Season %d, as the game does'
            % (SEASON_CONVAR, raw, where, latest))
        return latest, '%s %r is not a season: the latest' % (SEASON_CONVAR, raw)
    return n, '%s %d, %s' % (SEASON_CONVAR, n, where)


# --------------------------------------------------------------------------
# the AWS CLI
# --------------------------------------------------------------------------

AWS_FALLBACKS = (
    # A systemd unit's PATH has no /snap/bin, and both boxes install the CLI
    # as a snap.
    '/snap/bin/aws',
    '/usr/local/bin/aws',
    '/usr/bin/aws',
    r'C:\Program Files\Amazon\AWSCLIV2\aws.exe',
)


def find_aws(explicit: str | None = None) -> str:
    if explicit:
        return explicit
    found = shutil.which('aws')
    if found:
        return found
    if os.environ.get('BR_ASSETS_NO_AWS_FALLBACK'):
        raise AssetsError('the AWS CLI is not on PATH')
    for c in AWS_FALLBACKS:
        if os.path.isfile(c) and os.access(c, os.X_OK):
            return c
    raise AssetsError('the AWS CLI was not found on PATH or at /snap/bin/aws; install it or name it with --aws PATH')


def last_line(text: str) -> str:
    lines = [ln.strip() for ln in text.splitlines() if ln.strip()]
    return lines[-1] if lines else '(no message)'


class Aws:
    """The three calls this tool makes, through the CLI."""

    def __init__(self, exe: str, profile: str | None, region: str, bucket: str):
        # A .py stand-in (tools/test_assets.py's fake) is run by this
        # interpreter; the real CLI never is one.
        self.cmd = [sys.executable, exe] if exe.lower().endswith('.py') else [exe]
        self.tail = ['--region', region] + (['--profile', profile] if profile else [])
        self.bucket = bucket
        self.profile = profile

    def _run(self, args: list[str]) -> subprocess.CompletedProcess:
        env = dict(os.environ)
        env['AWS_PAGER'] = ''
        try:
            return subprocess.run(self.cmd + args + self.tail, stdout=subprocess.PIPE,
                                  stderr=subprocess.PIPE, env=env)
        except OSError as e:
            raise AssetsError('cannot run the AWS CLI (%s): %s' % (self.cmd[-1], e))

    def url(self, key: str) -> str:
        return 's3://%s/%s' % (self.bucket, key)

    def head(self, key: str) -> int | None:
        """The object's size, or None when there is no such object."""
        r = self._run(['s3api', 'head-object', '--bucket', self.bucket, '--key', key, '--output', 'json'])
        err = r.stderr.decode('utf-8', 'replace')
        if r.returncode == 0:
            try:
                return int(json.loads(r.stdout.decode('utf-8', 'replace'))['ContentLength'])
            except (ValueError, KeyError, TypeError):
                raise AssetsError('unexpected answer from aws s3api head-object for %s' % self.url(key))
        if '(404)' in err or 'Not Found' in err:
            return None
        if '(403)' in err or 'Forbidden' in err:
            raise AssetsError('access denied reading %s -- check the %s'
                              % (self.url(key), 'profile %r' % self.profile if self.profile else "box's instance role"))
        raise AssetsError('aws s3api head-object %s failed: %s' % (self.url(key), last_line(err)))

    def download(self, key: str, dest: str) -> None:
        r = self._run(['s3', 'cp', self.url(key), dest, '--no-progress', '--only-show-errors'])
        if r.returncode != 0:
            raise AssetsError('downloading %s failed: %s' % (self.url(key), last_line(r.stderr.decode('utf-8', 'replace'))))

    def upload(self, src: str, key: str) -> None:
        r = self._run(['s3', 'cp', src, self.url(key), '--no-progress', '--only-show-errors'])
        if r.returncode != 0:
            raise AssetsError('uploading %s failed: %s' % (self.url(key), last_line(r.stderr.decode('utf-8', 'replace'))))


def make_aws(args, default_profile: str | None = None) -> Aws:
    profile = default_profile if args.profile is None else args.profile
    if profile is not None and profile.lower() == 'none':
        profile = None
    return Aws(find_aws(args.aws), profile, args.region, args.bucket)


# --------------------------------------------------------------------------
# push
# --------------------------------------------------------------------------

UNSET = object()


def apply_push(lock: dict, name: str, sha: str, size: int, files: dict[str, int],
               season: int, frm=UNSET, until=UNSET) -> list[str]:
    """Pin `sha` at `season` for `name`, in place. What changed, in words."""
    changes: list[str] = []
    entry = next((e for e in lock['resources'] if e['name'] == name), None)
    if entry is None:
        entry = {'name': name, 'seasons': {}, 'versions': {}}
        lock['resources'].append(entry)
        changes.append('%s: new resource' % name)
    key = str(season)
    old = entry['seasons'].get(key)
    if old != sha:
        entry['seasons'][key] = sha
        changes.append('%s: Season %d and later -> %s%s'
                       % (name, season, short(sha), (' (was %s)' % short(old)) if old else ''))
    entry['versions'][sha] = {'size': size, 'files': dict(files)}
    for k, v in (('from', frm), ('until', until)):
        if v is UNSET:
            continue
        if v is None:
            if k in entry:
                del entry[k]
                changes.append('%s: "%s" cleared' % (name, k))
        elif entry.get(k) != v:
            entry[k] = v
            changes.append('%s: "%s" %d' % (name, k, v))
    live = set(entry['seasons'].values())
    for s in list(entry['versions']):
        if s not in live:
            del entry['versions'][s]
            changes.append('%s: %s is pinned to no season now; dropped from the lock '
                           '(its archive stays in the bucket)' % (name, short(s)))
    return changes


def cmd_push(args) -> int:
    folder = os.path.abspath(args.folder)
    if not os.path.isdir(folder):
        raise AssetsError('not a folder: %s' % folder)
    if not os.path.isfile(os.path.join(folder, 'fxmanifest.lua')):
        raise AssetsError('%s has no fxmanifest.lua; push takes one FiveM resource folder' % folder)
    name = args.name or os.path.basename(folder.rstrip('/\\'))
    if not NAME_RE.match(name):
        raise AssetsError('%r is not a resource name (letters, digits, _ and -); rename the folder or pass --name' % name)

    lock_path = args.lock
    names = repo_resource_names()
    if name.lower() == RECORD_RESOURCE:
        raise AssetsError('%s is reserved for the install record; rename the folder or pass --name' % name)
    if name.lower() in names:
        raise AssetsError('a resource in this repository already has the name %s; rename the folder '
                          'or pass --name' % name)
    lock = load_lock(lock_path, names)
    entry = next((e for e in lock['resources'] if e['name'] == name), None)
    if args.season is not None:
        season = args.season
    elif entry is None:
        season = 1
    elif len(entry['seasons']) == 1:
        season = int(next(iter(entry['seasons'])))
    else:
        raise AssetsError('%s pins versions at Seasons %s; say which one this is with --season N'
                          % (name, ', '.join(sorted(entry['seasons'], key=int))))

    with tempfile.TemporaryDirectory(prefix='assets-push-') as tmp:
        archive = os.path.join(tmp, 'pack.tar.gz')
        files, skipped = pack(folder, archive)
        sha, size = sha256_file(archive)
        say('packed %s: %d files, %s -> %s archive' % (name, len(files), human(sum(files.values())), human(size)))
        say('  sha256 %s' % sha)
        for s in skipped:
            say('  left out: %s' % s)

        # THE LOCK THIS PUSH WOULD WRITE, CHECKED BEFORE ANYTHING IS UPLOADED,
        # so a refusal leaves the bucket as well as the lock as they were.
        updated = json.loads(json.dumps(lock))
        changes = apply_push(updated, name, sha, size, files, season, args.from_season, args.until_season)
        problems = validate(updated, names)
        if problems:
            raise AssetsError('the lock would not pass check after this push; nothing was uploaded or written:\n%s'
                              % '\n'.join('  ' + x for x in problems))

        aws = make_aws(args, PUSH_PROFILE)
        key = object_key(name, sha)
        have = aws.head(key)
        if have is None:
            say('uploading %s to %s' % (human(size), aws.url(key)))
            aws.upload(archive, key)
            got = aws.head(key)
            if got != size:
                raise AssetsError('the upload did not land whole: %s holds %s bytes, the archive is %d'
                                  % (aws.url(key), got, size))
            say('uploaded')
        elif have == size:
            say('already in the bucket, not uploaded again: %s' % aws.url(key))
        else:
            raise AssetsError('%s already exists with %d bytes, not %d. Objects are never overwritten; '
                              'nothing was changed.' % (aws.url(key), have, size))

    text = dump_lock(updated)
    before = read_bytes(lock_path)
    if before is not None and before.replace(b'\r\n', b'\n') == text.encode('utf-8'):
        say('%s unchanged: %s is already pinned there' % (os.path.basename(lock_path), name))
        return 0
    atomic_write(lock_path, text)
    for c in changes:
        say('  ' + c)
    say('%s updated. Nothing was committed: review it, then commit it.' % os.path.basename(lock_path))
    return 0


# --------------------------------------------------------------------------
# pull
# --------------------------------------------------------------------------

def read_record(licensed: str) -> dict[str, str] | None:
    raw = read_bytes(os.path.join(licensed, RECORD_RESOURCE, RECORD_FILE))
    if raw is None:
        return None
    rec: dict[str, str] = {}
    for line in raw.decode('utf-8', 'replace').splitlines():
        t = line.split()
        if len(t) == 3 and t[0] == 'installed':
            rec[t[1]] = t[2]
    return rec


def record_text(lock: dict, season: int, latest: int, plan: list) -> str:
    """The install record br_core reads for brseason: what is installed, and
    what every season it could switch to would install instead."""
    seasons = list(range(1, latest + 1))
    if season not in seasons:
        seasons.append(season)
    lines = [
        '# GENERATED by tools/assets.py pull (#391). Do not edit: the next pull rewrites it.',
        '# br_core reads it so brseason can say when a switch needs other licensed assets.',
        'format 1',
        'season %d' % season,
        'seasons %s' % ' '.join(str(s) for s in seasons),
    ]
    for name, sha, _ in plan:
        lines.append('installed %s %s' % (name, sha))
    for s in seasons:
        for name, sha, _ in plan_for(lock, s):
            lines.append('plan %d %s %s' % (s, name, sha))
    return '\n'.join(lines) + '\n'


def cfg_text(season: int, plan: list) -> str:
    lines = [
        '# GENERATED by tools/assets.py pull (#391) for Season %d. Do not edit: the next pull rewrites it.' % season,
        '# server.cfg runs it with:  exec resources/%s/%s' % (LICENSED_GROUP, CFG_FILE),
    ]
    if not plan:
        lines.append('# Nothing licensed is installed for Season %d.' % season)
    for name, _, _ in plan:
        lines.append('ensure %s' % name)
    return '\n'.join(lines) + '\n'


def installed_dirs(licensed: str) -> list[str]:
    """The resource directories inside [licensed], and only there. The record
    resource is the tool's own and is never one of them."""
    if not os.path.isdir(licensed):
        return []
    out = []
    for entry in sorted(os.listdir(licensed)):
        full = os.path.join(licensed, entry)
        if entry == RECORD_RESOURCE or is_link(full) or not os.path.isdir(full):
            continue
        out.append(entry)
    return out


def fetch_verified(get_aws, cache: str, name: str, sha: str, size: int) -> tuple[str, str]:
    """THE ONLY DOOR TO AN ARCHIVE. Its path in the cache once its bytes are
    known to hash to `sha`, downloading it first if it is missing or does not.
    Raises, leaving nothing behind, when the bucket's copy does not match."""
    final = os.path.join(cache, name, sha + '.tar.gz')
    if os.path.isfile(final):
        got, n = sha256_file(final)
        if got == sha and n == size:
            return final, 'cached'
        say('  %s: the cached archive does not match its sha256; downloading it again' % name)
        os.remove(final)
    os.makedirs(os.path.dirname(final), exist_ok=True)
    part = '%s.part-%d' % (final, os.getpid())
    try:
        get_aws().download(object_key(name, sha), part)
        got, n = sha256_file(part)
        if got != sha or n != size:
            raise AssetsError('%s: the archive in the bucket does not match assets.lock\n'
                              '  want sha256 %s (%d bytes)\n'
                              '  got  sha256 %s (%d bytes)\n'
                              '  Nothing was unpacked and nothing installed was changed.'
                              % (name, sha, size, got, n))
        os.replace(part, final)
    finally:
        if os.path.exists(part):
            os.remove(part)
    return final, 'downloaded %s' % human(size)


@contextlib.contextmanager
def held(cache: str):
    """One pull at a time per cache."""
    os.makedirs(cache, exist_ok=True)
    fh = open(os.path.join(cache, '.lock'), 'a+')
    try:
        try:
            import fcntl
        except ImportError:
            fcntl = None
        if fcntl is not None:
            try:
                fcntl.flock(fh, fcntl.LOCK_EX | fcntl.LOCK_NB)
            except OSError:
                raise AssetsError('another pull is running (it holds %s)' % os.path.join(cache, '.lock'))
        yield
    finally:
        fh.close()


def commit(licensed: str, staging: str, trash: str, installs: list[str], removals: list[str],
           writes: list[tuple[str, str]]) -> None:
    """Swap the staged resources in and the stale ones out, then write the
    record and licensed.cfg. Any failure undoes every step taken so far, so the
    installed set is either all old or all new."""
    moved: list[tuple[str, str]] = []
    created: list[str] = []
    restored: list[tuple[str, bytes | None]] = []

    def move(a: str, b: str) -> None:
        os.rename(a, b)
        moved.append((a, b))

    try:
        for name in removals:
            move(os.path.join(licensed, name), os.path.join(trash, name))
        for name in installs:
            target = os.path.join(licensed, name)
            if os.path.lexists(target):
                move(target, os.path.join(trash, name))
            move(os.path.join(staging, name), target)
        rec_dir = os.path.join(licensed, RECORD_RESOURCE)
        if not os.path.isdir(rec_dir):
            os.makedirs(rec_dir)
            created.append(rec_dir)
        for path, text in writes:
            restored.append((path, read_bytes(path)))
            atomic_write(path, text)
    except BaseException:
        for path, old in reversed(restored):
            try:
                if old is None:
                    if os.path.exists(path):
                        os.remove(path)
                else:
                    with open(path, 'wb') as fh:
                        fh.write(old)
            except OSError:
                pass
        for d in reversed(created):
            shutil.rmtree(d, ignore_errors=True)
        for a, b in reversed(moved):
            os.rename(b, a)
        raise


def cmd_pull(args) -> int:
    server_root = os.path.abspath(args.server_root)
    resources = os.path.join(server_root, 'resources')
    if not os.path.isdir(resources):
        raise AssetsError('no resources/ under %s -- wrong --server-root?' % server_root)
    licensed = os.path.join(resources, LICENSED_GROUP)
    cache = os.path.abspath(args.cache) if args.cache else os.path.join(server_root, CACHE_DIR)

    lock = load_lock(args.lock)
    latest = read_latest()
    season, how = resolve_season(args, server_root, latest)
    plan = plan_for(lock, season)
    record = read_record(licensed) or {}
    present = installed_dirs(licensed)
    wanted = {name for name, _, _ in plan}

    say('Season %d (%s): %d licensed resource(s) in force' % (season, how, len(plan)))

    installs: list[tuple[str, str, dict]] = []
    for name, sha, ver in plan:
        target = os.path.join(licensed, name)
        if record.get(name) == sha and os.path.isdir(target) and dir_files(target) == ver['files']:
            say('  = %s %s' % (name, short(sha)))
            continue
        cached = os.path.isfile(os.path.join(cache, name, sha + '.tar.gz'))
        was = record.get(name)
        verb = '~' if name in present else '+'
        detail = (' (was %s)' % short(was)) if (was and was != sha) else (' (reinstall)' if was == sha else '')
        say('  %s %s %s%s, %s' % (verb, name, short(sha), detail,
                                  'cached' if cached else 'to download, %s' % human(ver['size'])))
        installs.append((name, sha, ver))
    removals = [d for d in present if d not in wanted]
    for d in removals:
        say('  - %s (not in force for Season %d)' % (d, season))

    if args.dry_run:
        say('dry run: nothing was downloaded or changed')
        return 0
    if not plan and not os.path.isdir(licensed):
        say('nothing licensed for Season %d and nothing installed; nothing to do' % season)
        return 0

    rec_dir = os.path.join(licensed, RECORD_RESOURCE)
    writes = [
        (os.path.join(rec_dir, 'fxmanifest.lua'), RECORD_MANIFEST),
        (os.path.join(rec_dir, RECORD_FILE), record_text(lock, season, latest, plan)),
        (os.path.join(licensed, CFG_FILE), cfg_text(season, plan)),
    ]
    if not installs and not removals and all(read_bytes(p) == t.encode('utf-8') for p, t in writes):
        say('up to date')
        return 0

    aws_box: list[Aws] = []

    def get_aws() -> Aws:
        if not aws_box:
            aws_box.append(make_aws(args))
        return aws_box[0]

    with held(cache):
        # 1. EVERY ARCHIVE, VERIFIED, BEFORE ANYTHING IS UNPACKED.
        archives: dict[str, str] = {}
        for name, sha, ver in installs:
            path, how_got = fetch_verified(get_aws, cache, name, sha, ver['size'])
            archives[name] = path
            say('  %s %s: sha256 verified (%s)' % (name, short(sha), how_got))
        os.makedirs(licensed, exist_ok=True)
        if os.stat(cache).st_dev != os.stat(licensed).st_dev:
            raise AssetsError('%s and %s are on different filesystems, so the swap cannot be atomic; '
                              'pass --cache with a directory beside resources/' % (cache, licensed))
        staging = tempfile.mkdtemp(prefix='.staging-', dir=cache)
        trash = tempfile.mkdtemp(prefix='.trash-', dir=cache)
        try:
            # 2. UNPACKED BESIDE THE CACHE, never inside resources/.
            for name, sha, ver in installs:
                unpack(archives[name], os.path.join(staging, name), ver['files'])
            # 3. SWAPPED IN, all or nothing.
            commit(licensed, staging, trash, [n for n, _, _ in installs], removals, writes)
        finally:
            shutil.rmtree(staging, ignore_errors=True)
            shutil.rmtree(trash, ignore_errors=True)

    say('installed for Season %d: %s' % (season, ', '.join(n for n, _, _ in plan) or 'nothing'))
    if installs or removals:
        say('licensed assets changed: they load on the next server restart')
    return 0


# --------------------------------------------------------------------------
# status and check
# --------------------------------------------------------------------------

def cmd_status(args) -> int:
    lock = load_lock(args.lock)
    say('%s: %d resource(s)' % (args.lock, len(lock['resources'])))
    aws = None if args.offline else make_aws(args)
    server_root = os.path.abspath(args.server_root) if args.server_root else None
    box = bool(server_root and os.path.isdir(os.path.join(server_root, 'resources')))
    licensed = os.path.join(server_root, 'resources', LICENSED_GROUP) if box else None
    cache = (os.path.abspath(args.cache) if args.cache else os.path.join(server_root, CACHE_DIR)) if box else None
    record = (read_record(licensed) or {}) if box else {}
    missing = 0
    for e in lock['resources']:
        bounds = ''.join(' %s %d' % (k, e[k]) for k in ('from', 'until') if k in e)
        say('%s%s' % (e['name'], bounds))
        for k in sorted(e['seasons'], key=int):
            sha = e['seasons'][k]
            ver = e['versions'][sha]
            facts = ['%s' % human(ver['size']), '%d files' % len(ver['files'])]
            if aws is not None:
                have = aws.head(object_key(e['name'], sha))
                if have is None:
                    facts.append('MISSING from the bucket')
                    missing += 1
                elif have != ver['size']:
                    facts.append('bucket holds %d bytes, not %d' % (have, ver['size']))
                    missing += 1
                else:
                    facts.append('in the bucket')
            if box:
                facts.append('cached' if os.path.isfile(os.path.join(cache, e['name'], sha + '.tar.gz')) else 'not cached')
                if record.get(e['name']) == sha:
                    facts.append('installed')
            say('  Season %s: %s  %s' % (k, short(sha), ', '.join(facts)))
    if box:
        latest = read_latest()
        season, how = resolve_season(args, server_root, latest)
        plan = plan_for(lock, season)
        say('this box: Season %d (%s)' % (season, how))
        for name, sha, _ in plan:
            have = record.get(name)
            state = 'installed' if have == sha else ('installed %s, lock says %s' % (short(have), short(sha)) if have else 'not installed')
            say('  %s %s: %s' % (name, short(sha), state))
        for d in installed_dirs(licensed):
            if d not in {n for n, _, _ in plan}:
                say('  %s: installed, not in force for Season %d (the next pull removes it)' % (d, season))
    if missing:
        say('%d archive(s) the lock names are not in the bucket' % missing)
        return 1
    return 0


def cmd_check(args) -> int:
    raw = read_bytes(args.lock)
    if raw is None:
        say('no %s: nothing to check' % os.path.basename(args.lock))
        return 0
    try:
        data = parse_lock_text(raw.decode('utf-8', 'replace'))
        problems = validate(data, repo_resource_names())
    except AssetsError as e:
        problems = [str(e)]
    if problems:
        for x in problems:
            print('FAIL %s: %s' % (os.path.basename(args.lock), x))
        return 1
    res = data['resources']
    nver = sum(len(e['versions']) for e in res)
    nfiles = sum(len(v['files']) for e in res for v in e['versions'].values())
    say('%s is valid: %d resource(s), %d version(s), %d file(s) listed'
        % (os.path.basename(args.lock), len(res), nver, nfiles))
    return 0


# --------------------------------------------------------------------------
# command line
# --------------------------------------------------------------------------

def season_arg(text: str) -> int:
    n = parse_season(text)
    if n is None:
        raise argparse.ArgumentTypeError('%r is not a season (a whole number from 1)' % text)
    return n


def season_or_none(text: str):
    if text.lower() == 'none':
        return None
    return season_arg(text)


def build_parser() -> argparse.ArgumentParser:
    common = argparse.ArgumentParser(add_help=False)
    common.add_argument('--lock', default=os.path.join(REPO_ROOT, LOCK_NAME),
                        help='the lock file (default: assets.lock at the repo root)')
    common.add_argument('--aws', help='the AWS CLI to run (default: aws on PATH, then /snap/bin/aws)')
    common.add_argument('--profile', help="AWS profile; 'none' for the instance role "
                                          "(default: %s for push, none otherwise)" % PUSH_PROFILE)
    common.add_argument('--region', default=REGION)
    common.add_argument('--bucket', default=BUCKET)

    box = argparse.ArgumentParser(add_help=False)
    box.add_argument('--server-root', default=os.environ.get('BR_SERVER_ROOT', DEFAULT_SERVER_ROOT),
                     help='the FXServer data directory (default: $BR_SERVER_ROOT or %s)' % DEFAULT_SERVER_ROOT)
    box.add_argument('--server-cfg', help='the cfg the season is read from (default: <server-root>/server.cfg)')
    box.add_argument('--season', type=season_arg, help="install for this season instead of server.cfg's")
    box.add_argument('--cache', help='archive cache (default: <server-root>/%s)' % CACHE_DIR)

    p = argparse.ArgumentParser(prog='assets.py', description='Licensed assets in the private bucket (#391).')
    sub = p.add_subparsers(dest='command', required=True)

    sp = sub.add_parser('push', parents=[common], help='pack a resource folder, upload it, pin it in the lock')
    sp.add_argument('folder')
    sp.add_argument('--name', help='resource name (default: the folder name)')
    sp.add_argument('--season', type=season_arg, help='pin this version from Season N on (default: 1, '
                                                      'or the only season the resource pins)')
    sp.add_argument('--from', dest='from_season', type=season_or_none, default=UNSET,
                    help="the resource's first season ('none' clears it)")
    sp.add_argument('--until', dest='until_season', type=season_or_none, default=UNSET,
                    help="the season it is off again from ('none' clears it)")
    sp.set_defaults(func=cmd_push)

    sp = sub.add_parser('pull', parents=[common, box], help="install the lock's resources for this box's season")
    sp.add_argument('--dry-run', action='store_true', help='print the plan; download and change nothing')
    sp.set_defaults(func=cmd_pull)

    sp = sub.add_parser('status', parents=[common, box], help='lock vs bucket (and vs this box), read-only')
    sp.add_argument('--offline', action='store_true', help='do not ask the bucket')
    sp.set_defaults(func=cmd_status)
    # status looks at a box only when it is asked to or is on one.
    sp.set_defaults(server_root=os.environ.get('BR_SERVER_ROOT')
                    or (DEFAULT_SERVER_ROOT if os.path.isdir(DEFAULT_SERVER_ROOT) else None))

    sp = sub.add_parser('check', parents=[common], help='validate the lock; never touches the bucket')
    sp.set_defaults(func=cmd_check)
    return p


def main(argv=None) -> int:
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(errors='replace')
        except (AttributeError, ValueError):
            pass
    args = build_parser().parse_args(argv)
    try:
        return args.func(args) or 0
    except AssetsError as e:
        lines = str(e).splitlines() or ['failed']
        print('assets: error: ' + lines[0], file=sys.stderr, flush=True)
        for line in lines[1:]:
            print(line, file=sys.stderr, flush=True)
        return 1
    except KeyboardInterrupt:
        return 130


if __name__ == '__main__':
    sys.exit(main())
